version: "3.9"
services:
  flf.com-ui:
    # build: .
    image: sdputurn/flf.com-ui
    # container_name: ui
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - br0

networks:
  br0:
    driver: bridge